language: python

python:
  - "2.7"

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - dev

install:
  - pip install pystache requests pygithub3 pygit2

script:
  - python generate.py

after_script:
  - python commit.py
