language: python

python:
  - "2.7"

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - dev

install:
  - wget https://github.com/libgit2/libgit2/archive/v0.24.2.tar.gz
  - tar xzf v0.24.2.tar.gz
  - cd libgit2-0.24.2/
  - cmake .
  - make
  - sudo make install
  - cd ../
  - pip install pystache requests pygithub3 pygit2

script:
  - python generate.py

after_script:
  - python commit.py
