language: python

python:
  - "2.7"

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - dev

install:
  - pip install pystache requests pygithub3

script:
  - python generate.py
